name: Deploy Razor Pages to GitHub Pages

on:
  push:
    branches:
      - master   # Change to your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x   # Change to your desired .NET version

      - name: Build and publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish/wwwroot